version: "2"

run:
  timeout: 3m

# Formatters (were linters in v1)
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    # set your module path(s) if you want local imports grouped separately
    goimports:
      local-prefixes:
        - github.com/MathieuMoalic/amumax/src

linters:
  enable:
    - revive
    - misspell
    - staticcheck
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: if-return
        - name: indent-error-flow
        - name: blank-imports
        - name: useless-break
        - name: package-comments

issues:
  exclude-use-default: false
