version: "2"

run:
  timeout: 3m

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/MathieuMoalic/amumax/src

linters:
  enable:
    - revive
    - misspell
    - staticcheck
  settings:
    govet:
      disable:
        - unsafeptr
    revive:
      rules:
        # - name: exported
        - name: var-naming
        - name: if-return
        - name: indent-error-flow
        - name: blank-imports
        - name: useless-break
        - name: package-comments

issues:
  exclude-use-default: false
