package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for pointwise_div kernel
var pointwiseDivCode cu.Function

// Stores the arguments for pointwise_div kernel invocation
type pointwiseDivArgsT struct {
	argDst unsafe.Pointer
	argA   unsafe.Pointer
	argB   unsafe.Pointer
	argN   int
	argptr  [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for pointwise_div kernel invocation
var pointwiseDivArgs pointwiseDivArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	pointwiseDivArgs.argptr[0] = unsafe.Pointer(&pointwiseDivArgs.argDst)
	pointwiseDivArgs.argptr[1] = unsafe.Pointer(&pointwiseDivArgs.argA)
	pointwiseDivArgs.argptr[2] = unsafe.Pointer(&pointwiseDivArgs.argB)
	pointwiseDivArgs.argptr[3] = unsafe.Pointer(&pointwiseDivArgs.argN)
}

// Wrapper for pointwise_div CUDA kernel, asynchronous.
func kPointwiseDivAsync(dst unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("pointwise_div")
	}

	pointwiseDivArgs.Lock()
	defer pointwiseDivArgs.Unlock()

	if pointwiseDivCode == 0 {
		pointwiseDivCode = fatbinLoad(pointwiseDivMap, "pointwise_div")
	}

	pointwiseDivArgs.argDst = dst
	pointwiseDivArgs.argA = a
	pointwiseDivArgs.argB = b
	pointwiseDivArgs.argN = N

	args := pointwiseDivArgs.argptr[:]
	cu.LaunchKernel(pointwiseDivCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("pointwise_div")
	}
}

// maps compute capability on PTX code for pointwise_div kernel.
var pointwiseDivMap = map[int]string{
	0:  "",
	52: pointwiseDivPtx52,
}

// pointwise_div PTX code for various compute capabilities.
const (
	pointwiseDivPtx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	pointwise_div

.visible .entry pointwise_div(
	.param .u64 pointwise_div_param_0,
	.param .u64 pointwise_div_param_1,
	.param .u64 pointwise_div_param_2,
	.param .u32 pointwise_div_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<10>;
	.reg .b64 	%rd<12>;


	ld.param.u64 	%rd2, [pointwise_div_param_0];
	ld.param.u64 	%rd3, [pointwise_div_param_1];
	ld.param.u64 	%rd4, [pointwise_div_param_2];
	ld.param.u32 	%r2, [pointwise_div_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_4;

	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r1, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	setp.neu.f32	%p2, %f1, 0f00000000;
	cvta.to.global.u64 	%rd8, %rd2;
	add.s64 	%rd1, %rd8, %rd6;
	@%p2 bra 	BB0_3;
	bra.uni 	BB0_2;

BB0_3:
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd11, %rd9, %rd6;
	ld.global.nc.f32 	%f2, [%rd11];
	div.rn.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd1], %f3;
	bra.uni 	BB0_4;

BB0_2:
	mov.u32 	%r9, 0;
	st.global.u32 	[%rd1], %r9;

BB0_4:
	ret;
}


`
)
