package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for madd2 kernel
var madd2Code cu.Function

// Stores the arguments for madd2 kernel invocation
type madd2ArgsT struct {
	argDst  unsafe.Pointer
	argSrc1 unsafe.Pointer
	argFac1 float32
	argSrc2 unsafe.Pointer
	argFac2 float32
	argN    int
	argptr  [6]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for madd2 kernel invocation
var madd2Args madd2ArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	madd2Args.argptr[0] = unsafe.Pointer(&madd2Args.argDst)
	madd2Args.argptr[1] = unsafe.Pointer(&madd2Args.argSrc1)
	madd2Args.argptr[2] = unsafe.Pointer(&madd2Args.argFac1)
	madd2Args.argptr[3] = unsafe.Pointer(&madd2Args.argSrc2)
	madd2Args.argptr[4] = unsafe.Pointer(&madd2Args.argFac2)
	madd2Args.argptr[5] = unsafe.Pointer(&madd2Args.argN)
}

// Wrapper for madd2 CUDA kernel, asynchronous.
func kMadd2Async(dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, fac2 float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("madd2")
	}

	madd2Args.Lock()
	defer madd2Args.Unlock()

	if madd2Code == 0 {
		madd2Code = fatbinLoad(madd2Map, "madd2")
	}

	madd2Args.argDst = dst
	madd2Args.argSrc1 = src1
	madd2Args.argFac1 = fac1
	madd2Args.argSrc2 = src2
	madd2Args.argFac2 = fac2
	madd2Args.argN = N

	args := madd2Args.argptr[:]
	cu.LaunchKernel(madd2Code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("madd2")
	}
}

// maps compute capability on PTX code for madd2 kernel.
var madd2Map = map[int]string{
	0:  "",
	52: madd2Ptx52,
}

// madd2 PTX code for various compute capabilities.
const (
	madd2Ptx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	madd2

.visible .entry madd2(
	.param .u64 madd2_param_0,
	.param .u64 madd2_param_1,
	.param .f32 madd2_param_2,
	.param .u64 madd2_param_3,
	.param .f32 madd2_param_4,
	.param .u32 madd2_param_5
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<7>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [madd2_param_0];
	ld.param.u64 	%rd2, [madd2_param_1];
	ld.param.f32 	%f1, [madd2_param_2];
	ld.param.u64 	%rd3, [madd2_param_3];
	ld.param.f32 	%f2, [madd2_param_4];
	ld.param.u32 	%r2, [madd2_param_5];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd4, %rd2;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f3, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd8, %rd7, %rd5;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f5, %f4, %f2;
	fma.rn.f32 	%f6, %f3, %f1, %f5;
	cvta.to.global.u64 	%rd9, %rd1;
	add.s64 	%rd10, %rd9, %rd5;
	st.global.f32 	[%rd10], %f6;

BB0_2:
	ret;
}


`
)
