package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for madd3 kernel
var madd3Code cu.Function

// Stores the arguments for madd3 kernel invocation
type madd3ArgsT struct {
	argDst  unsafe.Pointer
	argSrc1 unsafe.Pointer
	argFac1 float32
	argSrc2 unsafe.Pointer
	argFac2 float32
	argSrc3 unsafe.Pointer
	argFac3 float32
	argN    int
	argptr   [8]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for madd3 kernel invocation
var madd3Args madd3ArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	madd3Args.argptr[0] = unsafe.Pointer(&madd3Args.argDst)
	madd3Args.argptr[1] = unsafe.Pointer(&madd3Args.argSrc1)
	madd3Args.argptr[2] = unsafe.Pointer(&madd3Args.argFac1)
	madd3Args.argptr[3] = unsafe.Pointer(&madd3Args.argSrc2)
	madd3Args.argptr[4] = unsafe.Pointer(&madd3Args.argFac2)
	madd3Args.argptr[5] = unsafe.Pointer(&madd3Args.argSrc3)
	madd3Args.argptr[6] = unsafe.Pointer(&madd3Args.argFac3)
	madd3Args.argptr[7] = unsafe.Pointer(&madd3Args.argN)
}

// Wrapper for madd3 CUDA kernel, asynchronous.
func kMadd3Async(dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, fac2 float32, src3 unsafe.Pointer, fac3 float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("madd3")
	}

	madd3Args.Lock()
	defer madd3Args.Unlock()

	if madd3Code == 0 {
		madd3Code = fatbinLoad(madd3Map, "madd3")
	}

	madd3Args.argDst = dst
	madd3Args.argSrc1 = src1
	madd3Args.argFac1 = fac1
	madd3Args.argSrc2 = src2
	madd3Args.argFac2 = fac2
	madd3Args.argSrc3 = src3
	madd3Args.argFac3 = fac3
	madd3Args.argN = N

	args := madd3Args.argptr[:]
	cu.LaunchKernel(madd3Code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("madd3")
	}
}

// maps compute capability on PTX code for madd3 kernel.
var madd3Map = map[int]string{
	0:  "",
	52: madd3Ptx52,
}

// madd3 PTX code for various compute capabilities.
const (
	madd3Ptx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	madd3

.visible .entry madd3(
	.param .u64 madd3_param_0,
	.param .u64 madd3_param_1,
	.param .f32 madd3_param_2,
	.param .u64 madd3_param_3,
	.param .f32 madd3_param_4,
	.param .u64 madd3_param_5,
	.param .f32 madd3_param_6,
	.param .u32 madd3_param_7
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<14>;


	ld.param.u64 	%rd1, [madd3_param_0];
	ld.param.u64 	%rd2, [madd3_param_1];
	ld.param.f32 	%f1, [madd3_param_2];
	ld.param.u64 	%rd3, [madd3_param_3];
	ld.param.f32 	%f2, [madd3_param_4];
	ld.param.u64 	%rd4, [madd3_param_5];
	ld.param.f32 	%f3, [madd3_param_6];
	ld.param.u32 	%r2, [madd3_param_7];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd5, %rd2;
	mul.wide.s32 	%rd6, %r1, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f4, [%rd7];
	cvta.to.global.u64 	%rd8, %rd3;
	add.s64 	%rd9, %rd8, %rd6;
	ld.global.nc.f32 	%f5, [%rd9];
	cvta.to.global.u64 	%rd10, %rd4;
	add.s64 	%rd11, %rd10, %rd6;
	ld.global.nc.f32 	%f6, [%rd11];
	mul.f32 	%f7, %f6, %f3;
	fma.rn.f32 	%f8, %f5, %f2, %f7;
	fma.rn.f32 	%f9, %f4, %f1, %f8;
	cvta.to.global.u64 	%rd12, %rd1;
	add.s64 	%rd13, %rd12, %rd6;
	st.global.f32 	[%rd13], %f9;

BB0_2:
	ret;
}


`
)
