package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for minimize kernel
var minimizeCode cu.Function

// Stores the arguments for minimize kernel invocation
type minimizeArgsT struct {
	argMx  unsafe.Pointer
	argMy  unsafe.Pointer
	argMz  unsafe.Pointer
	argM0x unsafe.Pointer
	argM0y unsafe.Pointer
	argM0z unsafe.Pointer
	argTx  unsafe.Pointer
	argTy  unsafe.Pointer
	argTz  unsafe.Pointer
	argDt  float32
	argN   int
	argptr [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for minimize kernel invocation
var minimizeArgs minimizeArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	minimizeArgs.argptr[0] = unsafe.Pointer(&minimizeArgs.argMx)
	minimizeArgs.argptr[1] = unsafe.Pointer(&minimizeArgs.argMy)
	minimizeArgs.argptr[2] = unsafe.Pointer(&minimizeArgs.argMz)
	minimizeArgs.argptr[3] = unsafe.Pointer(&minimizeArgs.argM0x)
	minimizeArgs.argptr[4] = unsafe.Pointer(&minimizeArgs.argM0y)
	minimizeArgs.argptr[5] = unsafe.Pointer(&minimizeArgs.argM0z)
	minimizeArgs.argptr[6] = unsafe.Pointer(&minimizeArgs.argTx)
	minimizeArgs.argptr[7] = unsafe.Pointer(&minimizeArgs.argTy)
	minimizeArgs.argptr[8] = unsafe.Pointer(&minimizeArgs.argTz)
	minimizeArgs.argptr[9] = unsafe.Pointer(&minimizeArgs.argDt)
	minimizeArgs.argptr[10] = unsafe.Pointer(&minimizeArgs.argN)
}

// Wrapper for minimize CUDA kernel, asynchronous.
func kMinimizeAsync(mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, m0x unsafe.Pointer, m0y unsafe.Pointer, m0z unsafe.Pointer, tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, dt float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("minimize")
	}

	minimizeArgs.Lock()
	defer minimizeArgs.Unlock()

	if minimizeCode == 0 {
		minimizeCode = fatbinLoad(minimizeMap, "minimize")
	}

	minimizeArgs.argMx = mx
	minimizeArgs.argMy = my
	minimizeArgs.argMz = mz
	minimizeArgs.argM0x = m0x
	minimizeArgs.argM0y = m0y
	minimizeArgs.argM0z = m0z
	minimizeArgs.argTx = tx
	minimizeArgs.argTy = ty
	minimizeArgs.argTz = tz
	minimizeArgs.argDt = dt
	minimizeArgs.argN = N

	args := minimizeArgs.argptr[:]
	cu.LaunchKernel(minimizeCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("minimize")
	}
}

// maps compute capability on PTX code for minimize kernel.
var minimizeMap = map[int]string{
	0:  "",
	52: minimizePtx52,
}

// minimize PTX code for various compute capabilities.
const (
	minimizePtx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	minimize

.visible .entry minimize(
	.param .u64 minimize_param_0,
	.param .u64 minimize_param_1,
	.param .u64 minimize_param_2,
	.param .u64 minimize_param_3,
	.param .u64 minimize_param_4,
	.param .u64 minimize_param_5,
	.param .u64 minimize_param_6,
	.param .u64 minimize_param_7,
	.param .u64 minimize_param_8,
	.param .f32 minimize_param_9,
	.param .u32 minimize_param_10
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<26>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<29>;


	ld.param.u64 	%rd1, [minimize_param_0];
	ld.param.u64 	%rd2, [minimize_param_1];
	ld.param.u64 	%rd3, [minimize_param_2];
	ld.param.u64 	%rd4, [minimize_param_3];
	ld.param.u64 	%rd5, [minimize_param_4];
	ld.param.u64 	%rd6, [minimize_param_5];
	ld.param.u64 	%rd7, [minimize_param_6];
	ld.param.u64 	%rd8, [minimize_param_7];
	ld.param.u64 	%rd9, [minimize_param_8];
	ld.param.f32 	%f1, [minimize_param_9];
	ld.param.u32 	%r2, [minimize_param_10];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd10, %rd4;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd11;
	cvta.to.global.u64 	%rd15, %rd6;
	add.s64 	%rd16, %rd15, %rd11;
	cvta.to.global.u64 	%rd17, %rd7;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd11;
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd11;
	ld.global.nc.f32 	%f2, [%rd18];
	ld.global.nc.f32 	%f3, [%rd20];
	mul.f32 	%f4, %f3, %f3;
	fma.rn.f32 	%f5, %f2, %f2, %f4;
	ld.global.nc.f32 	%f6, [%rd22];
	fma.rn.f32 	%f7, %f6, %f6, %f5;
	mul.f32 	%f8, %f1, %f1;
	mul.f32 	%f9, %f8, %f7;
	mov.f32 	%f10, 0f40800000;
	sub.f32 	%f11, %f10, %f9;
	ld.global.nc.f32 	%f12, [%rd12];
	mul.f32 	%f13, %f12, %f11;
	ld.global.nc.f32 	%f14, [%rd14];
	mul.f32 	%f15, %f14, %f11;
	ld.global.nc.f32 	%f16, [%rd16];
	mul.f32 	%f17, %f16, %f11;
	mul.f32 	%f18, %f1, 0f40800000;
	fma.rn.f32 	%f19, %f18, %f2, %f13;
	fma.rn.f32 	%f20, %f18, %f3, %f15;
	fma.rn.f32 	%f21, %f18, %f6, %f17;
	add.f32 	%f22, %f9, 0f40800000;
	div.rn.f32 	%f23, %f19, %f22;
	cvta.to.global.u64 	%rd23, %rd1;
	add.s64 	%rd24, %rd23, %rd11;
	st.global.f32 	[%rd24], %f23;
	div.rn.f32 	%f24, %f20, %f22;
	cvta.to.global.u64 	%rd25, %rd2;
	add.s64 	%rd26, %rd25, %rd11;
	st.global.f32 	[%rd26], %f24;
	div.rn.f32 	%f25, %f21, %f22;
	cvta.to.global.u64 	%rd27, %rd3;
	add.s64 	%rd28, %rd27, %rd11;
	st.global.f32 	[%rd28], %f25;

BB0_2:
	ret;
}


`
)
