package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for shiftbytes kernel
var shiftbytesCode cu.Function

// Stores the arguments for shiftbytes kernel invocation
type shiftbytesArgsT struct {
	argDst   unsafe.Pointer
	argSrc   unsafe.Pointer
	argNx    int
	argNy    int
	argNz    int
	argShx   int
	argClamp byte
	argptr    [7]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for shiftbytes kernel invocation
var shiftbytesArgs shiftbytesArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	shiftbytesArgs.argptr[0] = unsafe.Pointer(&shiftbytesArgs.argDst)
	shiftbytesArgs.argptr[1] = unsafe.Pointer(&shiftbytesArgs.argSrc)
	shiftbytesArgs.argptr[2] = unsafe.Pointer(&shiftbytesArgs.argNx)
	shiftbytesArgs.argptr[3] = unsafe.Pointer(&shiftbytesArgs.argNy)
	shiftbytesArgs.argptr[4] = unsafe.Pointer(&shiftbytesArgs.argNz)
	shiftbytesArgs.argptr[5] = unsafe.Pointer(&shiftbytesArgs.argShx)
	shiftbytesArgs.argptr[6] = unsafe.Pointer(&shiftbytesArgs.argClamp)
}

// Wrapper for shiftbytes CUDA kernel, asynchronous.
func kShiftbytesAsync(dst unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, shx int, clamp byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("shiftbytes")
	}

	shiftbytesArgs.Lock()
	defer shiftbytesArgs.Unlock()

	if shiftbytesCode == 0 {
		shiftbytesCode = fatbinLoad(shiftbytesMap, "shiftbytes")
	}

	shiftbytesArgs.argDst = dst
	shiftbytesArgs.argSrc = src
	shiftbytesArgs.argNx = Nx
	shiftbytesArgs.argNy = Ny
	shiftbytesArgs.argNz = Nz
	shiftbytesArgs.argShx = shx
	shiftbytesArgs.argClamp = clamp

	args := shiftbytesArgs.argptr[:]
	cu.LaunchKernel(shiftbytesCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("shiftbytes")
	}
}

// maps compute capability on PTX code for shiftbytes kernel.
var shiftbytesMap = map[int]string{
	0:  "",
	52: shiftbytesPtx52,
}

// shiftbytes PTX code for various compute capabilities.
const (
	shiftbytesPtx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	shiftbytes

.visible .entry shiftbytes(
	.param .u64 shiftbytes_param_0,
	.param .u64 shiftbytes_param_1,
	.param .u32 shiftbytes_param_2,
	.param .u32 shiftbytes_param_3,
	.param .u32 shiftbytes_param_4,
	.param .u32 shiftbytes_param_5,
	.param .u8 shiftbytes_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftbytes_param_0];
	ld.param.u64 	%rd2, [shiftbytes_param_1];
	ld.param.u32 	%r6, [shiftbytes_param_2];
	ld.param.u32 	%r7, [shiftbytes_param_3];
	ld.param.u32 	%r9, [shiftbytes_param_4];
	ld.param.u32 	%r8, [shiftbytes_param_5];
	ld.param.u8 	%rs4, [shiftbytes_param_6];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r16, %r17, %r18;
	setp.lt.s32	%p1, %r1, %r6;
	setp.lt.s32	%p2, %r2, %r7;
	and.pred  	%p3, %p1, %p2;
	setp.lt.s32	%p4, %r3, %r9;
	and.pred  	%p5, %p3, %p4;
	@!%p5 bra 	BB0_4;
	bra.uni 	BB0_1;

BB0_1:
	sub.s32 	%r4, %r1, %r8;
	setp.lt.s32	%p6, %r4, 0;
	setp.ge.s32	%p7, %r4, %r6;
	or.pred  	%p8, %p6, %p7;
	mad.lo.s32 	%r19, %r3, %r7, %r2;
	mul.lo.s32 	%r5, %r19, %r6;
	@%p8 bra 	BB0_3;

	cvta.to.global.u64 	%rd3, %rd2;
	add.s32 	%r20, %r5, %r4;
	cvt.s64.s32	%rd4, %r20;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.u8 	%rs4, [%rd5];

BB0_3:
	cvta.to.global.u64 	%rd6, %rd1;
	add.s32 	%r21, %r5, %r1;
	cvt.s64.s32	%rd7, %r21;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.u8 	[%rd8], %rs4;

BB0_4:
	ret;
}


`
)
