name: release-artifacts

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Build
        run: |
          nix build .#release
          cp result/bin/amumax ./amumax
          chmod +x amumax

      - name: Publish to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: amumax
